[default]
timeout = 120

[naverpost]
title = "네이버 포스트 ─ 코스모폴리탄 코리아"
url = "https://post.naver.com/my.naver?memberNo=11800362"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"
onFail = "stale"

[fashion]
title = "코스모폴리탄 코리아 ─ 패션"
url = "https://www.cosmopolitan.co.kr/fashion"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
onFail = "stale"

[beauty]
title = "코스모폴리탄 코리아 ─ 뷰티"
url = "https://www.cosmopolitan.co.kr/beauty"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
onFail = "stale"

[celebs]
title = "코스모폴리탄 코리아 ─ 셀레브리티"
url = "https://www.cosmopolitan.co.kr/celebs"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
onFail = "stale"

[love]
title = "코스모폴리탄 코리아 ─ 러브"
url = "https://www.cosmopolitan.co.kr/love"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
onFail = "stale"

[life]
title = "코스모폴리탄 코리아 ─ 라이프"
url = "https://www.cosmopolitan.co.kr/life"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
onFail = "stale"

[cofficial]
title = "코스모폴리탄 코리아 ─ 코피셜"
url = "https://www.cosmopolitan.co.kr/cofficial"
entrySelector = "div.articlebox"
titleSelector = "em.title a"
linkSelector = "em a"
contentSelector = "p.excerpt a"
imageSelector = "div.imgbox.Thumb455"
waitForSelector = ".articlebox"
onFail = "stale"
